### PR TITLE
Metrics webapp development

### PR DESCRIPTION
**Pull request by dev-mamun**
**In This PR**

-  Designed the home and details page
-  Create unit tests for pure functions in your Redux code.
-  Create integration tests using the React Testing Library
-  Store data retrieved from the API in the Redux store
-  Every page has a unique route within the SPA

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Mamun, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that capstone project worked on by a single contributor should have Pull Request flow **from feature into development**. Kindly use the correct gitflow and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by dev-mamun — COMMENTED** [review]
this capstone did not require individual feature submission review @rloterh . i think you make a mistake.

**Review by andersonlebon — COMMENTED** [review]
## Hi @dev-mamun 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow the correct flow. In the requirement of the project, it is said that you need to use [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) and according to this flow on Microverse in individual projects, the submission for review should come from the `feature branch` to the dev branch.

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by dev-mamun** [comment]
> ## Hi @dev-mamun
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that does not follow the correct flow. In the requirement of the project, it is said that you need to use [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) and according to this flow on Microverse in individual projects, the submission for review should come from the `feature branch` to the dev branch.
> 
> image
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

@andersonlebon I think you do mistake

**Review by Nemwel-Boniface — COMMENTED** [review]
## Hello @dev-mamun   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request about your previous reviewers @rloterh and @andersonlebon . KIndly note that the reviewers were not wrong in invalidating your project because the flow that you currently used is wrong. Kindly note the following:

1. For group capstone projects the correct flow for requesting reviews is Github flow which means dev merging to main. (In this case, your project used the correct flow.
2. For solo capstone projects the flow for requesting reviews is Gitflow which means feature branch merging to dev.

Your project lies in the "Solo capstone" category and thus the flow which was required to be followed is GitFlow and not GitHub flow as it currently is.

For this reason, you will have the following options:

1. To create a new branch and open a new PR that merges to dev (The easy way around).
2. To rename the branches. [Here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) is the official docs on renaming branches. **Caveat:** I would suggest trying this in a separate repo before attempting to do this so that you understand what happens before making the change on this repo.

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

**Pull request merged**
